name: Deploy to EC2

on:
  push:
    branches: [ main ]  # main 브랜치에 푸시될 때 실행


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Add EC2 host to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/member

            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi

            git pull origin main
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            sudo systemctl restart nginx
            pkill gunicorn || true
            gunicorn -b 127.0.0.1:5000 app:app -D
          EOF
